/********************************************************************
* /Users/lucreziastellabruni/Dropbox/SCt_correlations/landau_gauss/cmake/main/LandauGaussDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /Users/lucreziastellabruni/Dropbox/SCt_correlations/landau_gauss/cmake/main/LandauGaussDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLandauGaussDict();
extern void G__cpp_setup_inheritanceLandauGaussDict();
extern void G__cpp_setup_typetableLandauGaussDict();
extern void G__cpp_setup_memvarLandauGaussDict();
extern void G__cpp_setup_globalLandauGaussDict();
extern void G__cpp_setup_memfuncLandauGaussDict();
extern void G__cpp_setup_funcLandauGaussDict();
extern void G__set_cpp_environmentLandauGaussDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/Users/lucreziastellabruni/Dropbox/SCt_correlations/landau_gauss/main/include/landgausFit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LandauGaussDictLN_TClass;
extern G__linked_taginfo G__LandauGaussDictLN_TBuffer;
extern G__linked_taginfo G__LandauGaussDictLN_TMemberInspector;
extern G__linked_taginfo G__LandauGaussDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LandauGaussDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LandauGaussDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__LandauGaussDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__LandauGaussDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LandauGaussDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__LandauGaussDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__LandauGaussDictLN_TF1;
extern G__linked_taginfo G__LandauGaussDictLN_TGraphErrors;
extern G__linked_taginfo G__LandauGaussDictLN_TH1D;
extern G__linked_taginfo G__LandauGaussDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__LandauGaussDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__LandauGaussDictLN_landgausFit;

/* STUB derived class for protected member access */
