//
// File generated by /Users/lucreziastellabruni/Downloads/root/bin/rootcint at Tue Jul 14 17:01:56 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIUsersdIlucreziastellabrunidIDropboxdISCt_correlationsdIlandau_gaussdIcmakedImaindILandauGaussDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "LandauGaussDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void landgausFit_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_landgausFit(void *p = 0);
   static void *newArray_landgausFit(Long_t size, void *p);
   static void delete_landgausFit(void *p);
   static void deleteArray_landgausFit(void *p);
   static void destruct_landgausFit(void *p);
   static void streamer_landgausFit(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::landgausFit*)
   {
      ::landgausFit *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::landgausFit >(0);
      static ::ROOT::TGenericClassInfo 
         instance("landgausFit", ::landgausFit::Class_Version(), "/Users/lucreziastellabruni/Dropbox/SCt_correlations/landau_gauss/main/include/landgausFit.h", 45,
                  typeid(::landgausFit), ::ROOT::DefineBehavior(ptr, ptr),
                  &::landgausFit::Dictionary, isa_proxy, 0,
                  sizeof(::landgausFit) );
      instance.SetNew(&new_landgausFit);
      instance.SetNewArray(&newArray_landgausFit);
      instance.SetDelete(&delete_landgausFit);
      instance.SetDeleteArray(&deleteArray_landgausFit);
      instance.SetDestructor(&destruct_landgausFit);
      instance.SetStreamerFunc(&streamer_landgausFit);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::landgausFit*)
   {
      return GenerateInitInstanceLocal((::landgausFit*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::landgausFit*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr landgausFit::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *landgausFit::Class_Name()
{
   return "landgausFit";
}

//______________________________________________________________________________
const char *landgausFit::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::landgausFit*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int landgausFit::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::landgausFit*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void landgausFit::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::landgausFit*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *landgausFit::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::landgausFit*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void landgausFit::Streamer(TBuffer &R__b)
{
   // Stream an object of class landgausFit.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      R__b.CheckByteCount(R__s, R__c, landgausFit::IsA());
   } else {
      R__c = R__b.WriteVersion(landgausFit::IsA(), kTRUE);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void landgausFit::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class landgausFit.
      TClass *R__cl = ::landgausFit::IsA();
      if (R__cl || R__insp.IsA()) { }
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_landgausFit(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::landgausFit : new ::landgausFit;
   }
   static void *newArray_landgausFit(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::landgausFit[nElements] : new ::landgausFit[nElements];
   }
   // Wrapper around operator delete
   static void delete_landgausFit(void *p) {
      delete ((::landgausFit*)p);
   }
   static void deleteArray_landgausFit(void *p) {
      delete [] ((::landgausFit*)p);
   }
   static void destruct_landgausFit(void *p) {
      typedef ::landgausFit current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_landgausFit(TBuffer &buf, void *obj) {
      ((::landgausFit*)obj)->::landgausFit::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::landgausFit

/********************************************************
* /Users/lucreziastellabruni/Dropbox/SCt_correlations/landau_gauss/cmake/main/LandauGaussDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableLandauGaussDict();

extern "C" void G__set_cpp_environmentLandauGaussDict() {
  G__cpp_reset_tagtableLandauGaussDict();
}
#include <new>
extern "C" int G__cpp_dllrevLandauGaussDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* landgausFit */
static int G__LandauGaussDict_288_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   landgausFit* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new landgausFit[n];
     } else {
       p = new((void*) gvp) landgausFit[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new landgausFit;
     } else {
       p = new((void*) gvp) landgausFit;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LandauGaussDictLN_landgausFit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      ((landgausFit*) G__getstructoffset())->setStartValues((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ((landgausFit*) G__getstructoffset())->setStartValues((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((landgausFit*) G__getstructoffset())->setStartValues((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((landgausFit*) G__getstructoffset())->setStartValues((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((landgausFit*) G__getstructoffset())->setStartValues();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((landgausFit*) G__getstructoffset())->setStartAmplitude((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((landgausFit*) G__getstructoffset())->setStartAmplitude();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((landgausFit*) G__getstructoffset())->setStartLandauMean((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((landgausFit*) G__getstructoffset())->setStartLandauMean();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((landgausFit*) G__getstructoffset())->setStartLandauSigma((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((landgausFit*) G__getstructoffset())->setStartLandauSigma();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((landgausFit*) G__getstructoffset())->setStartGaussSigma((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((landgausFit*) G__getstructoffset())->setStartGaussSigma();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      ((landgausFit*) G__getstructoffset())->setLowerLimits((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ((landgausFit*) G__getstructoffset())->setLowerLimits((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((landgausFit*) G__getstructoffset())->setLowerLimits((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((landgausFit*) G__getstructoffset())->setLowerLimits((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((landgausFit*) G__getstructoffset())->setLowerLimits();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      ((landgausFit*) G__getstructoffset())->setUpperLimits((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ((landgausFit*) G__getstructoffset())->setUpperLimits((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((landgausFit*) G__getstructoffset())->setUpperLimits((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((landgausFit*) G__getstructoffset())->setUpperLimits((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((landgausFit*) G__getstructoffset())->setUpperLimits();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((landgausFit*) G__getstructoffset())->setLimits_Amplitude((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((landgausFit*) G__getstructoffset())->setLimits_Amplitude((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((landgausFit*) G__getstructoffset())->setLimits_Amplitude();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((landgausFit*) G__getstructoffset())->setLimits_LandauMP((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((landgausFit*) G__getstructoffset())->setLimits_LandauMP((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((landgausFit*) G__getstructoffset())->setLimits_LandauMP();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((landgausFit*) G__getstructoffset())->setLimits_LandauSigma((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((landgausFit*) G__getstructoffset())->setLimits_LandauSigma((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((landgausFit*) G__getstructoffset())->setLimits_LandauSigma();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((landgausFit*) G__getstructoffset())->setLimits_GaussSigma((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((landgausFit*) G__getstructoffset())->setLimits_GaussSigma((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((landgausFit*) G__getstructoffset())->setLimits_GaussSigma();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((landgausFit*) G__getstructoffset())->setFitOptions((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((landgausFit*) G__getstructoffset())->setFitRange((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((landgausFit*) G__getstructoffset())->setLandauGauss_Separation((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((landgausFit*) G__getstructoffset())->setLandauGauss_Separation();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((landgausFit*) G__getstructoffset())->getAmplitude());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((landgausFit*) G__getstructoffset())->getLandauMostProbable());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((landgausFit*) G__getstructoffset())->getLandauSigma());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((landgausFit*) G__getstructoffset())->getGaussSigma());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((landgausFit*) G__getstructoffset())->getErrorOfAmplitude());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((landgausFit*) G__getstructoffset())->getErrorOfLandauMP());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((landgausFit*) G__getstructoffset())->getErrorOfLandauSigma());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((landgausFit*) G__getstructoffset())->getErrorOfGaussSigma());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((landgausFit*) G__getstructoffset())->getChiSqare());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((landgausFit*) G__getstructoffset())->GetNDF());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 105, (long) ((landgausFit*) G__getstructoffset())->operator()((TGraphErrors*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 105, (long) ((landgausFit*) G__getstructoffset())->operator()((TGraphErrors*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((landgausFit*) G__getstructoffset())->operator()((TGraphErrors*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 105, (long) ((landgausFit*) G__getstructoffset())->operator()((TH1D*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 105, (long) ((landgausFit*) G__getstructoffset())->operator()((TH1D*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((landgausFit*) G__getstructoffset())->operator()((TH1D*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((landgausFit*) G__getstructoffset())->FastFit((TGraphErrors*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((landgausFit*) G__getstructoffset())->FastFit((TH1D*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((landgausFit*) G__getstructoffset())->DrawfitFunction((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((landgausFit*) G__getstructoffset())->printResults(*(ostream*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((landgausFit*) G__getstructoffset())->printResults();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((landgausFit*) G__getstructoffset())->saveFitToFile((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((landgausFit*) G__getstructoffset())->getLandauGauss());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) landgausFit::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) landgausFit::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) landgausFit::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      landgausFit::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const landgausFit*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((landgausFit*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((landgausFit*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((landgausFit*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) landgausFit::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) landgausFit::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) landgausFit::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LandauGaussDict_288_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) landgausFit::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__LandauGaussDict_288_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   landgausFit* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new landgausFit(*(landgausFit*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LandauGaussDictLN_landgausFit));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef landgausFit G__TlandgausFit;
static int G__LandauGaussDict_288_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (landgausFit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((landgausFit*) (soff+(sizeof(landgausFit)*i)))->~G__TlandgausFit();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (landgausFit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((landgausFit*) (soff))->~G__TlandgausFit();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__LandauGaussDict_288_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   landgausFit* dest = (landgausFit*) G__getstructoffset();
   *dest = *(landgausFit*) libp->para[0].ref;
   const landgausFit& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* landgausFit */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncLandauGaussDict {
 public:
  G__Sizep2memfuncLandauGaussDict(): p(&G__Sizep2memfuncLandauGaussDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncLandauGaussDict::*p)();
};

size_t G__get_sizep2memfuncLandauGaussDict()
{
  G__Sizep2memfuncLandauGaussDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceLandauGaussDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableLandauGaussDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__LandauGaussDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__LandauGaussDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* landgausFit */
static void G__setup_memvarlandgausFit(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__LandauGaussDictLN_landgausFit));
   { landgausFit *p; p=(landgausFit*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__LandauGaussDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarLandauGaussDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfunclandgausFit(void) {
   /* landgausFit */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__LandauGaussDictLN_landgausFit));
   G__memfunc_setup("landgausFit",1138,G__LandauGaussDict_288_0_1, 105, G__get_linked_tagnum(&G__LandauGaussDictLN_landgausFit), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setStartValues",1482,G__LandauGaussDict_288_0_2, 121, -1, -1, 0, 4, 1, 1, 0, 
"d - 'Double_t' 0 '1' Amplitude d - 'Double_t' 0 '200' landau_mean "
"d - 'Double_t' 0 '70' landau_sigma d - 'Double_t' 0 '10' gauss_sigma", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setStartAmplitude",1791,G__LandauGaussDict_288_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 '1' Amplitude", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setStartLandauMean",1840,G__LandauGaussDict_288_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 '200' landau_mean", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setStartLandauSigma",1952,G__LandauGaussDict_288_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 '70' landau_sigma", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setStartGaussSigma",1870,G__LandauGaussDict_288_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 '10' gaus_sigma", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLowerLimits",1479,G__LandauGaussDict_288_0_7, 121, -1, -1, 0, 4, 1, 1, 0, 
"d - 'Double_t' 0 '0' Amplitude d - 'Double_t' 0 '0' landau_mean "
"d - 'Double_t' 0 '0' landau_sigma d - 'Double_t' 0 '0' gauss_sigma", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setUpperLimits",1482,G__LandauGaussDict_288_0_8, 121, -1, -1, 0, 4, 1, 1, 0, 
"d - 'Double_t' 0 '2' Amplitude d - 'Double_t' 0 '1000' landau_mean "
"d - 'Double_t' 0 '1000' landau_sigma d - 'Double_t' 0 '1000' gauss_sigma", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLimits_Amplitude",1986,G__LandauGaussDict_288_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 '0' startValue d - 'Double_t' 0 '2' endValue", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLimits_LandauMP",1807,G__LandauGaussDict_288_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 '0' startValue d - 'Double_t' 0 '1000' endValue", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLimits_LandauSigma",2147,G__LandauGaussDict_288_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 '0' startValue d - 'Double_t' 0 '1000' endValue", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLimits_GaussSigma",2065,G__LandauGaussDict_288_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 '0' startValue d - 'Double_t' 0 '1000' endValue", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setFitOptions",1371,G__LandauGaussDict_288_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - options", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setFitRange",1116,G__LandauGaussDict_288_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - MinValue d - 'Double_t' 0 - MaxValue", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setLandauGauss_Separation",2585,G__LandauGaussDict_288_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 '100' separation", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getAmplitude",1253,G__LandauGaussDict_288_0_16, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getLandauMostProbable",2143,G__LandauGaussDict_288_0_17, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getLandauSigma",1414,G__LandauGaussDict_288_0_18, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getGaussSigma",1332,G__LandauGaussDict_288_0_19, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getErrorOfAmplitude",1956,G__LandauGaussDict_288_0_20, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getErrorOfLandauMP",1777,G__LandauGaussDict_288_0_21, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getErrorOfLandauSigma",2117,G__LandauGaussDict_288_0_22, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getErrorOfGaussSigma",2035,G__LandauGaussDict_288_0_23, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getChiSqare",1104,G__LandauGaussDict_288_0_24, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", "since for now there are no errors supported for the individual measuring points one can not apply ", (void*) NULL, 0);
   G__memfunc_setup("GetNDF",504,G__LandauGaussDict_288_0_25, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator()",957,G__LandauGaussDict_288_0_26, 105, -1, G__defined_typename("Int_t"), 0, 3, 1, 1, 0, 
"U 'TGraphErrors' - 0 - fitData i - 'Int_t' 0 '0' firstBin "
"i - 'Int_t' 0 '-1' Lastbin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator()",957,G__LandauGaussDict_288_0_27, 105, -1, G__defined_typename("Int_t"), 0, 3, 1, 1, 0, 
"U 'TH1D' - 0 - fitData i - 'Int_t' 0 '0' firstBin "
"i - 'Int_t' 0 '-1' Lastbin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FastFit",689,G__LandauGaussDict_288_0_28, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "U 'TGraphErrors' - 0 - fitData", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FastFit",689,G__LandauGaussDict_288_0_29, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "U 'TH1D' - 0 - fitData", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawfitFunction",1559,G__LandauGaussDict_288_0_30, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - channel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("printResults",1311,G__LandauGaussDict_288_0_31, 121, -1, -1, 0, 1, 1, 1, 0, "u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - out", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("printResults",1311,G__LandauGaussDict_288_0_32, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("saveFitToFile",1301,G__LandauGaussDict_288_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - fileName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getLandauGauss",1432,G__LandauGaussDict_288_0_34, 85, G__get_linked_tagnum(&G__LandauGaussDictLN_TF1), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__LandauGaussDict_288_0_35, 85, G__get_linked_tagnum(&G__LandauGaussDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&landgausFit::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__LandauGaussDict_288_0_36, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&landgausFit::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__LandauGaussDict_288_0_37, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&landgausFit::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__LandauGaussDict_288_0_38, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&landgausFit::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__LandauGaussDict_288_0_39, 85, G__get_linked_tagnum(&G__LandauGaussDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__LandauGaussDict_288_0_40, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__LandauGaussDict_288_0_41, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__LandauGaussDict_288_0_42, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__LandauGaussDict_288_0_43, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&landgausFit::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__LandauGaussDict_288_0_44, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&landgausFit::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__LandauGaussDict_288_0_45, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&landgausFit::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__LandauGaussDict_288_0_46, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&landgausFit::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("landgausFit", 1138, G__LandauGaussDict_288_0_47, (int) ('i'), G__get_linked_tagnum(&G__LandauGaussDictLN_landgausFit), -1, 0, 1, 1, 1, 0, "u 'landgausFit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~landgausFit", 1264, G__LandauGaussDict_288_0_48, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__LandauGaussDict_288_0_49, (int) ('u'), G__get_linked_tagnum(&G__LandauGaussDictLN_landgausFit), -1, 1, 1, 1, 1, 0, "u 'landgausFit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncLandauGaussDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalLandauGaussDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcLandauGaussDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__LandauGaussDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__LandauGaussDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TF1 = { "TF1" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TGraphErrors = { "TGraphErrors" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__LandauGaussDictLN_landgausFit = { "landgausFit" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableLandauGaussDict() {
  G__LandauGaussDictLN_TClass.tagnum = -1 ;
  G__LandauGaussDictLN_TBuffer.tagnum = -1 ;
  G__LandauGaussDictLN_TMemberInspector.tagnum = -1 ;
  G__LandauGaussDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LandauGaussDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LandauGaussDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__LandauGaussDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__LandauGaussDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LandauGaussDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__LandauGaussDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__LandauGaussDictLN_TF1.tagnum = -1 ;
  G__LandauGaussDictLN_TGraphErrors.tagnum = -1 ;
  G__LandauGaussDictLN_TH1D.tagnum = -1 ;
  G__LandauGaussDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__LandauGaussDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__LandauGaussDictLN_landgausFit.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableLandauGaussDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TF1);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TGraphErrors);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_TMatrixTBaselEdoublegR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__LandauGaussDictLN_landgausFit),sizeof(landgausFit),-1,1280,(char*)NULL,G__setup_memvarlandgausFit,G__setup_memfunclandgausFit);
}
extern "C" void G__cpp_setupLandauGaussDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupLandauGaussDict()");
  G__set_cpp_environmentLandauGaussDict();
  G__cpp_setup_tagtableLandauGaussDict();

  G__cpp_setup_inheritanceLandauGaussDict();

  G__cpp_setup_typetableLandauGaussDict();

  G__cpp_setup_memvarLandauGaussDict();

  G__cpp_setup_memfuncLandauGaussDict();
  G__cpp_setup_globalLandauGaussDict();
  G__cpp_setup_funcLandauGaussDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncLandauGaussDict();
  return;
}
class G__cpp_setup_initLandauGaussDict {
  public:
    G__cpp_setup_initLandauGaussDict() { G__add_setup_func("LandauGaussDict",(G__incsetup)(&G__cpp_setupLandauGaussDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initLandauGaussDict() { G__remove_setup_func("LandauGaussDict"); }
};
G__cpp_setup_initLandauGaussDict G__cpp_setup_initializerLandauGaussDict;

